### ISSUE TITLE
为什么不评估zero-shot的性能呢

### ISSUE THREAD

**Issue by yyht** [SJTU-LIT/ceval#1]
您好，非常棒的工作。几个问题：
1. 只有five-shot的评估，five-shot的选择和顺序，不同的few-shot 对结果的影响 有进一步分析么
2. 有zero-shot的评估么，
3. 后续会提供 人工的cot 过程么？以及 是否发布一定量的train-dataset

**Comment by Nipi64310** [comment]
顺便问一下，后续会提供val的评测对比吗，val评测结果同test差异有多大

**Comment by jxhe** [comment]
感谢各位兴趣哈，以下是我们的回复：

> 只有five-shot的评估

我们在第一个版本首先关注few-shot因为 1. 我们认为大模型的in-context learning能力很重要; 2. few-shot更容易测出模型*潜力*，尤其是没有经过instruction tuning的模型可能无法很好follow zero-shot instruction。我们倾向于认为few-shot场景下强的模型可以经过简单的instruction tuning把相关能力反映在zero-shot和few-shot的下游任务中（比如LLaMA在MMLU上的表现）；3. 参考了英文MMLU的数据集广泛被应用于five-shot测试；4. few-shot使模型follow固定格式回答问题这样测试更标准，避免了因为提取不出答案误判

> five-shot的选择和顺序，不同的few-shot 对结果的影响 有进一步分析么

这个我们没有做进一步分析，我们就是按照dev split公开的5个样本作为few-shot，顺序就是按照数据集默认的顺序

> 有zero-shot的评估么

在计划添加zero-shot的评估

> 后续会提供 人工的cot 过程么？以及 是否发布一定量的train-dataset

dev里面的数据有人工cot，paper里有详细描述我们怎么做的。我们没有train dataset，不过[这里](https://github.com/FlagOpen/FlagInstruct)的中文instruction tuning数据集包含了一些初高中和公务员的多选题，也许有帮助

> 后续会提供val的评测对比吗（因为test必须提交才能看到分数），val评测结果同test差异有多大

Paper里有val的评测对比，结论是同test差异不太大

**Comment by jxhe** [comment]
已经添加zero-shot的评估结果
