### ISSUE TITLE
疑问：是否对齐不同模型之间结果

### ISSUE THREAD

**Issue by Desein-Yang** [SJTU-LIT/ceval#10]
您好，很棒的开源评测基准数据，有几处疑问感觉不同模型结果没有严格对齐

1.  chatGLM 和 minimax 和 Moss ChatGPT  cot 答案解析中正则匹配不一致，严格程度不同，这可能对结果有比较大的影响。模型生成非标准答案文本时（如"选xx"）究竟算作对还是错。
2. 最大长度是怎么处理的，一些学科答案过长，moss 等本地推理的模型没有做截断操作，而生成长度设为 2040-inputs.input_ids.shape[1] 可能=0 ，导致部分学科分数偏低。
3. 能否放出其他模型各单项结果，以便分析对比某一专业能力

**Comment by jxhe** [comment]
感谢提问！以下是我们的回复：

> 1. chatGLM 和 minimax 和 Moss ChatGPT cot 答案解析中正则匹配不一致，严格程度不同，这可能对结果有比较大的影响。模型生成非标准答案文本时（如"选xx"）究竟算作对还是错。  

我们通过正则表达式尽可能cover了所有的pattern，在提取答案的时候我们有计算“提取成功率”，确保了几乎100%的题目我们都有提取出答案选项。无法提取出答案的情况确实cot要多一些，但很多时候这种情况是因为cot自己并没有回答问题。我们的原则是要尽可能去提取出答案，不要出现“误判”

> 2. 最大长度是怎么处理的，一些学科答案过长，moss 等本地推理的模型没有做截断操作，而生成长度设为 2040-inputs.input_ids.shape[1] 可能=0 ，导致部分学科分数偏低。

在answer-only的场景下所有模型都几乎没有长度的问题，cot的场景下很多模型确实出现了长度问题，这主要是因为我们做的five-shot。我们的方式是动态调整shot的数量来适应长度限制，比如moss在高等数学这样的科目上我们做cot只用了one-shot。受到影响的科目不多，只有少数高数、概率统计、法学等cot很长的科目。我们目前也在测zero-shot的结果，zero-shot下应该就几乎没有长度问题了。

> 3. 能否放出其他模型各单项结果，以便分析对比某一专业能力

在我们网站的leaderboard上的所有模型的单项结果都可以看到（点击对应模型名字即可）：https://cevalbenchmark.com/static/leaderboard.html

**Comment by Desein-Yang** [comment]
明白了，感谢解答！我们在自己模型评估时出于对齐的考虑，没有针对模型答案匹配、全部 5-shot，发现了以上问题，目前也是采用灵活处理 cot 情况下左边样本截断。为了直接和放出其他模型对比，请问这里方便给出哪些任务采用了 one-shot 处理吗？

> 比如moss在高等数学这样的科目上我们做cot只用了one-shot。受到影响的科目不多，只有少数高数、概率统计、法学等cot很长的科目。

**Comment by jxhe** [comment]
不同模型其实不一样，因为有些模型可以用更长的context我们就没有用one-shot，我们是动态调整的，并没有统一这一点。我们用one-shot的case应该基本是高数、概率统计、法学这三个cot很长的科目
