### ISSUE TITLE
Chinese Alpaca-13B怎么会比Chinese LLama-13B 效果差呢？

### ISSUE THREAD

**Issue by liuyukid** [SJTU-LIT/ceval#11]
Alpaca还经过了指令微调，按理来说不应该比llama差呀

**Comment by jxhe** [comment]
在Alpaca数据集上的指令微调我们认为只是增强了模型理解并follow zero-shot instruction的能力，并没有实质学到新的ceval需要的能力（alpaca数据集应该是不太包括ceval考核的相关知识）。再加上我们目前的结果是few-shot结果，alpaca的微调方式我们认为一定程度上牺牲了few-shot in-context learning的能力。
