### ISSUE TITLE
[Enhancement]: 有计划把ceval集成在openai的evals框架下面吗

### ISSUE THREAD

**Issue by rgtjf** [SJTU-LIT/ceval#12]
非常好的开源评测基准，有计划把ceval集成在openai的evals框架下面吗，这样可能会减少学习成本

**Comment by jxhe** [comment]
我们看了一下集成到openai的evals似乎需要同时release我们的test labels，但是我们暂时没有release test labels的计划

**Comment by rgtjf** [comment]
谢谢回复，比如用validation labels做验证呢，不用test labels。

**Comment by HYZ17** [comment]
我们认为目前已经覆盖了最常见的两种使用方式，因此没有相关的计划，感谢您的建议

**Comment by jxhe** [comment]
@rgtjf 不好意思，我们重新讨论了一下，使用validation labels做验证加到openai evals应该是可行且值得做的，最近我们会尝试集成一下，会把更新post到这里，敬请期待~

**Comment by xTayEx** [comment]
> @rgtjf 不好意思，我们重新讨论了一下，使用validation labels做验证加到openai evals应该是可行且值得做的，最近我们会尝试集成一下，会把更新post到这里，敬请期待~

请问目前是否有相关进展呢

**Comment by HYZ17** [comment]
我们把ceval加在了[lm-evaluation-harness](https://github.com/EleutherAI/lm-evaluation-harness)下，欢迎体验。
