### ISSUE TITLE
提交文件的疑惑

### ISSUE THREAD

**Issue by guozhiyao** [SJTU-LIT/ceval#13]
请问下，我看测试题目都是选择题。是手动将模型的输出结果转化为选项，然后再提交的吗？模型输出通常不止包含选项。

**Comment by jxhe** [comment]
是的，因为不同的模型输出风格都不太一样，所以需要自己从模型的输出中提取出答案选项再提交。我们评测的时候是通过正则表达式提取答案的，确保了几乎100%的题目都可以提取出答案选项

**Comment by guozhiyao** [comment]
> 是的，因为不同的模型输出风格都不太一样，所以需要自己从模型的输出中提取出答案选项再提交。我们评测的时候是通过正则表达式提取答案的，确保了几乎100%的题目都可以提取出答案选项

@jxhe 请问这个正则表达式能否提供下呢？

**Comment by Phosphor-Bai** [comment]
正则表达式可以参考evaluator中的代码：https://github.com/SJTU-LIT/ceval/blob/aa73be2bccf016297b09508cad7cc226b9b91e0e/code/evaluator_series/evaluators/chatglm.py#LL77C9-L77C9

**Comment by guozhiyao** [comment]
感谢
