### ISSUE TITLE
测试结果的波动

### ISSUE THREAD

**Issue by guozhiyao** [SJTU-LIT/ceval#15]
你好，我尝试测试了下val的准确率，但是由于模型生成时是采样的形式，所以准确率会出现波动。你们在测试时有发现这个现象吗？

**Comment by jxhe** [comment]
我们基本都是用的greedy decoding，随机性较小

**Comment by guozhiyao** [comment]
> 我们基本都是用的greedy decoding，随机性较小

@jxhe 请问你们有对比过sample形式的吗？是否发现greedy比sample的结果要好？

**Comment by jxhe** [comment]
我们用chatgpt在几个科目上做过对比是greedy更好，这里也参照了MMLU官方的测试代码是用的greedy decoding: 

https://github.com/hendrycks/test/blob/4450500f923c49f1fb1dd3d99108a0bd9717b660/evaluate.py#L67

**Comment by FranxYao** [comment]
Greedy decoding 可以被认为是国际标准做法，GSM8K, BBH, MMLU, MATH 都是这么做的
https://github.com/FranxYao/chain-of-thought-hub/tree/main

在大部分数据集上， Greedy decoding 一般都会比 sample 好一些（但不多） -- 起决定性作用的还是基础模型的能力
