### ISSUE TITLE
prompt不同的疑惑？

### ISSUE THREAD

**Issue by cason0126** [SJTU-LIT/ceval#16]
比较了chatglm和moss这2个本地LLM的eval代码，从代码看，Prompt会有所不同，这会对结果有影响吗？
另外代码中没有看到Chinese-Alpaca-13B的eval代码，这部分是没有公开吗？

**Comment by HYZ17** [comment]
主要的结构是一样的。但是，MOSS官方示例中包含meta_instruction的部分，因此我们也添加了这部分内容（与openai的system message 相似）。而chatglm并不包含类似内容，因此两者略有不同，但是主体一致。
