### ISSUE TITLE
为什么leadbord中模型的结果比之前好很多呢？

### ISSUE THREAD

**Issue by guozhiyao** [SJTU-LIT/ceval#17]
https://cevalbenchmark.com/static/leaderboard.html
为什么leadbord里的结果比readme里的结果突然变高了很多呢？

**Comment by DaoD** [comment]
部分经过了SFT的模型zero shot性能会优于few shot。leadboard里按照最高的结果更新了一版。

**Comment by guozhiyao** [comment]
> 部分经过了SFT的模型zero shot性能会优于few shot。leadboard里按照最高的结果更新了一版。

那zero shot方式的话，模型回答的答案好提取吗？是不是正则要写更多？

**Comment by DaoD** [comment]
我刚刚提了个issue问他们这个问题
#18

**Comment by jxhe** [comment]
部分模型的zero-shot答案提取还行，比如chatgpt和moss等都是直接输出了答案token，可以做到几乎100%的提取准确率，gpt-4通过正则表达式也可以做到几乎100%。如果开发者测试自己模型时发现zero-shot很难提取的话，我们推荐直接计算A,B,C,D的概率选最大的那个作为答案，[MMLU的官方测试代码](https://github.com/hendrycks/test/blob/4450500f923c49f1fb1dd3d99108a0bd9717b660/evaluate.py#L88)就是这么做的的，我们对于GLM130B, chatGLM, LLaMA等模型也是这么计算的。

**Comment by guozhiyao** [comment]
> 部分模型的zero-shot答案提取还行，比如chatgpt和moss等都是直接输出了答案token，可以做到几乎100%的提取准确率，gpt-4通过正则表达式也可以做到几乎100%。如果开发者测试自己模型时发现zero-shot很难提取的话，我们推荐直接计算下个token预测"A","B","C","D"的概率选最大的那个作为答案，[MMLU的官方测试代码](https://github.com/hendrycks/test/blob/4450500f923c49f1fb1dd3d99108a0bd9717b660/evaluate.py#L88)就是这么做的，我们对于GLM130B, chatGLM, LLaMA等模型也是这么计算的。

@jxhe 请问能提供下chatGLM zero-shot的测试代码吗？

**Comment by Phosphor-Bai** [comment]
已更新，具体位置在这里（简单改写了chatglm原有的generate_dist函数）：https://github.com/SJTU-LIT/ceval/blob/558edaaa177e0e6f58d9839b63684dfbc884fe0a/code/evaluator_series/evaluators/chatglm.py#L43
