### ISSUE TITLE
想参与annotation工作，以前是高中物理老师，现在香港读MPhil，求捞

### ISSUE THREAD

**Issue by lyconghk** [SJTU-LIT/ceval#32]
1. 本人去年刚来香港读MPhil（刚准备转PhD），大论文具体研究方向还没确定，所以有点烦和比较慌。
2. 以前是高中物理老师，由于某些不可抗力的原因不干了，所以比较懂里面考试题的trick，可以干一些annotation的work。
3. 编程能看懂和写一点python，但不精。
4. 现在没人带，想参与这个CEVAL项目，积累一点项目经验。
5. 我的email:  lyconghk@hotmail.com,    wechat:    lyconghk

**Comment by jxhe** [comment]
您好，感谢您的兴趣！目前ceval第一阶段的标注任务已经结束，当下暂时没有其他标注任务，之后如果有需求的话我们再与您联系，谢谢！
