### ISSUE TITLE
根据code/Readme.md中给出的示例尝试遇到问题

### ISSUE THREAD

**Issue by yixin-zhu** [SJTU-LIT/ceval#33]
按照code/Readme.md中给出的方法，放置了data文件夹，并一路安装所有依赖，但是之后尝试其中给出的示例遇到了问题

1 moss的问题，按图中的指令，显示如下报错

这似乎是因为没有使用tie_weights()造成的

![image](https://github.com/SJTU-LIT/ceval/assets/67551555/cba168b6-5ce5-4f37-aa3e-6343f3bcc581)

2 chatglm的问题，按图中的指令，显示如下报错

没有任何切片被加载，这看起来不同寻常，是否是因为内存不够
![image](https://github.com/SJTU-LIT/ceval/assets/67551555/3dcbfb21-5a74-4d1e-baa9-500df831a8ff)

我使用的是Ubuntu20.04，Python 3.8.10，所有依赖都直接用sudo pip install安装

我在大模型这个领域缺乏经验，感谢您的回答

**Comment by HYZ17** [comment]
在我的环境下MOSS的代码可以正常运行。我检索到与你类似的问题（参考https://github.com/artidoro/qlora/issues/151#issuecomment-1631744267），可能是accelerate库的问题；你可以将accelerate 库进行降级，降为0.19.0或者0.18.0（我的环境）重新运行，希望可以解决问题

**Comment by Phosphor-Bai** [comment]
如果在运行ChatGLM-6B的时候直接报了Killed，应该是内存不够。看起来你是在笔记本电脑上运行的程序，或许可以考虑使用服务器运行代码。
