### ISSUE TITLE
题目错误

### ISSUE THREAD

**Issue by AiLMe-AI** [SJTU-LIT/ceval#36]
teacher_qualification_test.csv 中，第138题：

138,男同学小陈平时自由散漫，学习不认真，一天在课堂上用手机给班上的女同学发短信“曾某，我爱你”，被上课的王老师发现。王老师收缴了小陈的手机，并将短信内容向全班同学宣读，同时指责其“思想堕落，道德败坏”。下课后小陈要求王老师归还手机，王老师说，这是罪证不能归还，要交给学校德育处。校长指出王老师：①未经学生同意翻看短信侵犯了学生的隐私权；②批评的话语侵犯了学生的人格权；③收缴手机侵犯了学生的财产权；④作为老师不能以违法的方式对待学生的违纪行为。你认为校长的说法正确的是____。,蝙蝠,鲸,蜂鸟,海豹

选项和问题没有关系

**Comment by HYZ17** [comment]
感谢反馈，我们会在近期更正，谢谢
