### ISSUE TITLE
art_studies_test.csv 中有题目错误

### ISSUE THREAD

**Issue by AiLMe-AI** [SJTU-LIT/ceval#38]
art_studies_test.csv 中，第178题：

178,qp世纪的主要戏剧不包括____。,奇迹剧,神秘剧,广场剧,道德剧

这里的【qp世纪】，推测来自 cqvip.com的《在职艺术硕士（MFA）全国联考戏剧学》试题，原题目有笔误，结果其它网站以讹传讹Copy-Paste的时候也抄错了，实际没有【qp世纪】这个说法。cqvip.com的《在职艺术硕士（MFA）全国联考戏剧学》试题的正确答案是C，而奇迹剧、神秘剧和道德剧是欧洲中世纪的戏剧形式，因此建议修改题目为：

欧洲中世纪的主要戏剧不包括____。

**Comment by HYZ17** [comment]
感谢您的反馈，我们会在近期进行更新
