### ISSUE TITLE
middle_school_history_test.csv 中有题目错误

### ISSUE THREAD

**Issue by AiLMe-AI** [SJTU-LIT/ceval#40]
middle_school_history_test.csv，第82题：

82,在右图所示的残垣断壁是历史上哪一次侵华战争的见证____。,鸦片战争,第二次鸦片战争,甲午中日战争,八国联军侵华战争

题目中说“右图”，但并没有图片。经查证，此题来自广东省广州高山文化培训学校 2014-2015 学年八年级历史上学期期中试题，原题是一张圆明园的图片。

建议题目修改为：著名的圆明园“大水法”的残垣断壁是历史上哪一次侵华战争的见证____。

**Comment by AiLMe-AI** [comment]
补充：advanced_mathematics_test.csv 文件，第68题：

68,计算定积分：$I=\int_0^{\pi}{\sqrt{\sin x-\sin^2x}\mathrm{d}x}$____,$2\sqrt{2}+\ln \left( \frac{\sqrt{2}-1}{\sqrt{2}+1} \right)$,$2\sqrt{2}+\ln \left( \frac{\sqrt{2}-1}{\sqrt{2}+1} \right)$,$2\sqrt{2}+\ln \left( \frac{\sqrt{2}-1}{\sqrt{2}+1} \right)$,$2\sqrt{2}+\ln \left( \frac{\sqrt{2}-1}{\sqrt{2}+1} \right)$

该题A, B, C, D四个选项完全一样，因此无法选择正确答案。

**Comment by HYZ17** [comment]
感谢您的反馈，我们会在近期进行更新
