### ISSUE TITLE
lm-evaluation-harness 是用test集测评的吗？

### ISSUE THREAD

**Issue by ChangyuanWu** [SJTU-LIT/ceval#44]
你好，最近我在用lm-evaluation-harness进行模型测评。
但是根据lm-evaluation-harness的task_table显示只有val集并且数量较少。请问如果我使用lm-evaluation-harness进行测评的时候，会使用test集的结果评估，还是val的结果评估？
<img width="845" alt="image" src="https://github.com/SJTU-LIT/ceval/assets/57976018/592bfb3e-84db-45ba-8fa6-175652dfad94">

**Comment by HYZ17** [comment]
由于lm-evaluation-harness需要公开答案，因此我们使用的是val集。谢谢
