### ISSUE TITLE
chatglm2-6b在valid set上的zero-shot结果似乎有问题

### ISSUE THREAD

**Issue by ylwangy** [SJTU-LIT/ceval#46]
如题，我用lm-eval-harness发现chatglm2-6b的结果很差，0-shot下只有20多的准确率，是不是哪里出错了？
![image](https://github.com/SJTU-LIT/ceval/assets/31842494/6d980ee6-e57a-4368-9baa-06f82a07b34c)

**Comment by HYZ17** [comment]
首先，在lm-eval-harness中只有validation集，每一个科目下的题目数量较少，因此结果可能波动较大。在当初测试代码的时候，使用的是gpt3，结果正常。或许你可以尝试few-shot下的结果？

**Comment by ylwangy** [comment]
@HYZ17 感谢回复，我又用该Repo的代码跑了下ChatGLM2-6B在valid set上的zero-shot表现，发现也差不多，20出头。我同样的代码换成chatglm1-6b，是39多。比较正常。感觉2应该比1高才对。官方是否也可以尝试测一下，我不确认是否存在问题。
![image](https://github.com/SJTU-LIT/ceval/assets/31842494/2d6d81ed-ff16-459b-b8ea-e23b8bcc2b15)

**Comment by ylwangy** [comment]
感觉可能不是lm-eval-harness框架代码的问题，所以改了下标题。

**Comment by HYZ17** [comment]
这个原因尚且不清楚，可能需要查看一下chatglm2的测试方法
