### ISSUE TITLE
C-Eval 提交规则限制

### ISSUE THREAD

**Issue by suolyer** [SJTU-LIT/ceval#47]
哈喽，请问，C-Eval 提交有什么条件吗？必须GPT么，BERT不可以吗？期待回复^_^

**Comment by HYZ17** [comment]
您好！任何模型的结果都可以在我们的网站进行提交，然后获取对应的分数。具体参考：https://github.com/SJTU-LIT/ceval/blob/main/README_zh.md#%E5%A6%82%E4%BD%95%E6%8F%90%E4%BA%A4

**Comment by suolyer** [comment]
我提交了一版（submit- ID：9b1d7f35-3276-11ee-bd8b-00163e0166d9），也邮件回复了你们的疑问，leaderboard没有显示，也没有收到你们的邮件回复，所以不知道是什么情况，还盼有同学能够回答一下，感谢

**Comment by zzh068** [comment]
> 我提交了一版（submit- ID：9b1d7f35-3276-11ee-bd8b-00163e0166d9），也邮件回复了你们的疑问，leaderboard没有显示，也没有收到你们的邮件回复，所以不知道是什么情况，还盼有同学能够回答一下，感谢

你好～这个记录已经更新了～
