### ISSUE TITLE
申请公开

### ISSUE THREAD

**Issue by huayicong23** [SJTU-LIT/ceval#55]
您好，麻烦更新下leaderboard吧，辛苦了

**Comment by zzh068** [comment]
请问您提交的模型是什么？

**Comment by zzh068** [comment]
> 您好，麻烦更新下leaderboard吧，辛苦了

请问您提交的模型是什么？

**Comment by huayicong23** [comment]
> 

您好，id是3ffcaefa-42ee-11ee-bd8b-00163e0166d9。谢谢

**Comment by huayicong23** [comment]
> > 您好，麻烦更新下leaderboard吧，辛苦了
> 
> 请问您提交的模型是什么？

您好，id是3ffcaefa-42ee-11ee-bd8b-00163e0166d9。谢谢！

**Comment by zzh068** [comment]
> > > 您好，麻烦更新下leaderboard吧，辛苦了
> > 
> > 
> > 请问您提交的模型是什么？
> 
> 您好，id是3ffcaefa-42ee-11ee-bd8b-00163e0166d9。谢谢！

嗯嗯，更新了

**Comment by huayicong23** [comment]
> > > > 您好，麻烦更新下leaderboard吧，辛苦了
> > > 
> > > 
> > > 请问您提交的模型是什么？
> > 
> > 
> > 您好，id是3ffcaefa-42ee-11ee-bd8b-00163e0166d9。谢谢！
> 
> 嗯嗯，更新了

THKS!
