### ISSUE TITLE
You guys posted a hilarious Leaderboatd on your official website

### ISSUE THREAD

**Issue by stephonye** [SJTU-LIT/ceval#57]
Note the * and Note, hahaha, what's the point of actually submitting the scores by the users themselves?

The first 9 are some unheard of pheasants, it's hilarious!

https://cevalbenchmark.com/static/leaderboard.html

<img width="1510" alt="截屏2023-09-06 下午2 17 04" src="https://github.com/SJTU-LIT/ceval/assets/6421173/6a2dce58-865e-4eb8-ac76-908f62318fad">

**Comment by jxhe** [comment]
We welcome any feedback or discussion, but please be polite if you want to make a point or discussion anything
