### ISSUE TITLE
没有文心一言、讯飞星火、通义千问等已发布的大模型？

### ISSUE THREAD

**Issue by wqw547243068** [SJTU-LIT/ceval#7]
如题，是否有对比已发布的几家大模型？

**Comment by jxhe** [comment]
没有哈，部分商业模型我们暂时没有API权限。内测阶段我们有邀请一些商业模型测试，但是这两天准备正式发布了，因为一些考虑我们从leaderboard上下架了未公开的商业模型。

我们的数据集题目是公开的，我们会继续邀请和鼓励相关模型的开发人员到我们的网站上提交或者公开结果。

**Comment by yaleimeng** [comment]
放上去会影响别人公司的股价。。
作为学术研究性项目，还是让国产大模型自愿参与比较好。有兴趣的网友可以自己测试、交流。
