### ISSUE TITLE
请问LLaMA-65B在测试的时候，题目是英文输入还是中文输入？

### ISSUE THREAD

**Issue by cingtiye** [SJTU-LIT/ceval#9]

**Comment by puppet101** [comment]
llama的中文常识类问题不是很差么，从这个评测来看好像还可以？

**Comment by cingtiye** [comment]
> llama的中文常识类问题不是很差么，从这个评测来看好像还可以？

测的是选择题~之前不太好的测的应该不是65B的 是7B/13B的
